# Generated by Django 3.1.3 on 2020-11-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('ext_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=30, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('tests_id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_time', models.DateTimeField(blank=True, null=True, verbose_name='Назанченное время теста')),
                ('result_time', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время сдачи теста')),
                ('result', models.BooleanField(default=False, verbose_name='Результат: да/нет')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.personal')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_pub', models.DateField(auto_now=True, db_index=True)),
                ('data', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.personal')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
