# Generated by Django 3.1.3 on 2020-11-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='data',
        ),
        migrations.AddField(
            model_name='photo',
            name='data_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/poll', verbose_name='Фото'),
        ),
    ]
